formatting a bit

diff --git a/files/default/rt4-fcgi b/files/default/rt4-fcgi
--- a/files/default/rt4-fcgi
+++ b/files/default/rt4-fcgi
@@ -49,39 +49,39 @@ do_start()
     # Return
     #   0 if daemon has been started
     #   1 if daemon was already running
-#   2 if daemon could not be started
-#start-stop-daemon --start --quiet --pidfile $PIDFILE  --test > /dev/null \
-start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $PROGRAM --test > /dev/null \
-    || ( log_warning_msg ": $NAME is already running"; return 1 )
-start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS || return 0
-sleep 1
+    #   2 if daemon could not be started
+    #start-stop-daemon --start --quiet --pidfile $PIDFILE  --test > /dev/null \
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $PROGRAM --test > /dev/null \
+        || ( log_warning_msg ": $NAME is already running"; return 1 )
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS || return 0
+    sleep 1
 }
 
 # Function that stops the daemon/service
 do_stop()
 {
-# Return
-#   0 if daemon has been stopped
-#   1 if daemon was already stopped
-#   2 if daemon could not be stopped
-#   other if a failure occurred
-for PID in $(pgrep -f -d' ' $PROGRAM); do
-    echo "$PID">"$PIDFILE" && start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
-done
-RETVAL=$?
-rm -f $PIDFILE $SOCKFILE
-return $RETVAL
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    for PID in $(pgrep -f -d' ' $PROGRAM); do
+        echo "$PID">"$PIDFILE" && start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
+    done
+    RETVAL=$?
+    rm -f $PIDFILE $SOCKFILE
+    return $RETVAL
 }
 
 # Function that sends a SIGHUP to the daemon/service -- not implemented
 do_reload() {
-#
-# If the daemon can reload its configuration without
-# restarting (for example, when it is sent a SIGHUP),
-# then implement that here.
-#
-#start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --exec $DAEMON
-return 0
+    #
+    # If the daemon can reload its configuration without
+    # restarting (for example, when it is sent a SIGHUP),
+    # then implement that here.
+    #
+    #start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --exec $DAEMON
+    return 0
 }
 
 case "$1" in
